'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const { parse: parseFrontmatter } = require('../adapters/_shared/frontmatter.cjs');
const {
  CORE_PUBLIC_SKILLS,
  INTERNAL_AGENT_SKILLS,
  SUPPORTED_RUNTIMES,
  skillsForRuntime,
} = require('../adapters/_shared/runtime-assets.cjs');
const { WORKFLOW_DEFINITIONS } = require('../mcp-server/lib/workflow-state.cjs');

const ROOT = path.resolve(__dirname, '..');
const SKILLS_ROOT = path.join(ROOT, 'skills');
const COMMANDS_ROOT = path.join(ROOT, 'commands');
const AGENTS_ROOT = path.join(ROOT, 'agents');
const TEMPLATE_ROOTS = [path.join(ROOT, '.ultra-template'), path.join(ROOT, 'templates', '.ultra')];
const COLLAB_SKILLS = new Set(['cc-collab', 'codex-collab', 'ultra-verify']);
const PACKAGED_SKILLS = new Set(SUPPORTED_RUNTIMES.flatMap((runtime) => skillsForRuntime(runtime)));
const NEUTRAL_SKILLS = new Set([...CORE_PUBLIC_SKILLS, ...INTERNAL_AGENT_SKILLS]);

function walk(root, predicate = () => true) {
  const files = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const file = path.join(root, entry.name);
    if (entry.isDirectory()) files.push(...walk(file, predicate));
    else if (predicate(file)) files.push(file);
  }
  return files;
}

function sourceSkill(name) {
  const file = path.join(SKILLS_ROOT, name, 'SKILL.md');
  return { file, text: fs.readFileSync(file, 'utf8') };
}

test('skills directory contains only deliberately packaged skill roots', () => {
  const roots = fs.readdirSync(SKILLS_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  assert.deepEqual(roots, [...PACKAGED_SKILLS].sort());
});

test('source SKILL.md files use portable Agent Skills frontmatter', () => {
  for (const name of [...PACKAGED_SKILLS].sort()) {
    const { text } = sourceSkill(name);
    const { fm } = parseFrontmatter(text);
    assert.ok(fm, `${name} must have YAML frontmatter`);
    assert.deepEqual(Object.keys(fm).sort(), ['description', 'name'], `${name} has host/runtime metadata in SKILL.md`);
    assert.equal(fm.name, name, `${name} frontmatter name must match its directory`);
    assert.match(fm.description, /\bUse(?: only)? when\b/i, `${name} description must say when it should activate`);
    assert.ok(fm.description.length <= 1024, `${name} description exceeds Agent Skills limit`);
  }
});

test('packaged skill markdown is English and free of release-history prompt residue', () => {
  const forbidden = [
    { pattern: /[\u3400-\u9fff]/u, label: 'Han-script instruction text' },
    { pattern: /\bpre-Phase\b|\bPhase\s+\d+\.\d+\b|\bv4\.4\b|\bv4\.5\b/i, label: 'release or migration history' },
    { pattern: /\bContext7\b|mcp__context7|\bExa MCP\b|mcp__exa|\bGemini\b|\bRTK\b|\bgraphify\b/i, label: 'retired or external tool binding' },
    { pattern: /\b90%\+?\s+confidence\b|\b80%\s+overall\b|\b100%\s+Functional Core\b/i, label: 'unsupported global quality threshold' },
    { pattern: /\bFlag as\s+(?:an?\s+)?(?:P[0-3]|orphan|horizontal)|\bRequired Test\b|\/\/\s*(?:Bad|Good):/i, label: 'mechanical pattern-to-verdict teaching' },
    { pattern: /\bFunction\s*>\s*\d+\s+lines\b|\bNesting depth\s*>\s*\d+|\baggregate score\b/i, label: 'arbitrary design threshold' },
  ];

  for (const name of [...PACKAGED_SKILLS].sort()) {
    const files = walk(path.join(SKILLS_ROOT, name), (file) => file.endsWith('.md'));
    for (const file of files) {
      const text = fs.readFileSync(file, 'utf8');
      for (const { pattern, label } of forbidden) {
        assert.doesNotMatch(text, pattern, `${path.relative(ROOT, file)} contains ${label}`);
      }
    }
  }
});

test('project specification templates are neutral evidence records for greenfield and brownfield work', () => {
  const forbidden = [
    { pattern: /[\u3400-\u9fff]/u, label: 'Han-script instruction text' },
    { pattern: /Generated by .*Steps?\s+\d+|Validation Confidence|Overall:\s*\[.*\]%/i, label: 'retired staged prompt ceremony' },
    { pattern: /Pre-product\s*\/\s*Has users|Option B, Option C|Prioritized Opportunities \(Top 3\)/i, label: 'invented comparison or fixed choice menu' },
    { pattern: /gets them promoted|gets them fired|Emotional Arc|Porter'?s Five Forces|Functional Core \(pure logic\)/i, label: 'forced persona, framework, or architecture content' },
    { pattern: /Priority Score\s*=|Opportunity Score\s*=|Strength \(1-5\)|\/10/i, label: 'unsupported mechanical score' },
  ];
  for (const root of TEMPLATE_ROOTS) {
    for (const file of walk(path.join(root, 'specs'), (candidate) => candidate.endsWith('.md'))) {
      const text = fs.readFileSync(file, 'utf8');
      for (const { pattern, label } of forbidden) {
        assert.doesNotMatch(text, pattern, `${path.relative(ROOT, file)} contains ${label}`);
      }
      assert.match(text, /^## Observed$/m, `${path.relative(ROOT, file)} needs observed facts`);
      assert.match(text, /^## Decisions$/m, `${path.relative(ROOT, file)} needs explicit decisions`);
      assert.match(text, /^## Unknowns$/m, `${path.relative(ROOT, file)} needs unresolved boundaries`);
    }
  }
  const canonical = walk(TEMPLATE_ROOTS[0], (candidate) => candidate.endsWith('.md'))
    .map((file) => path.relative(TEMPLATE_ROOTS[0], file)).sort();
  const runtime = walk(TEMPLATE_ROOTS[1], (candidate) => candidate.endsWith('.md'))
    .map((file) => path.relative(TEMPLATE_ROOTS[1], file)).sort();
  assert.deepEqual(runtime, canonical, 'source and runtime template inventories must stay aligned');
  for (const rel of canonical) {
    assert.equal(
      fs.readFileSync(path.join(TEMPLATE_ROOTS[1], rel), 'utf8'),
      fs.readFileSync(path.join(TEMPLATE_ROOTS[0], rel), 'utf8'),
      `${rel} differs between source and runtime templates`,
    );
  }
});

test('every published Ultra project template is tracked by Git', () => {
  const runtimeFiles = walk(TEMPLATE_ROOTS[1])
    .map((file) => path.relative(TEMPLATE_ROOTS[1], file))
    .sort();
  for (const rel of runtimeFiles) {
    const publishedPath = path.relative(ROOT, path.join(TEMPLATE_ROOTS[0], rel));
    assert.doesNotThrow(
      () => execFileSync(
        'git',
        ['ls-files', '--error-unmatch', '--', publishedPath],
        { cwd: ROOT, stdio: 'pipe' },
      ),
      `${publishedPath} is present locally but missing from a clean npm package`,
    );
  }
});

test('core and internal skills are host-neutral', () => {
  const hostBindings = /\bClaude Code\b|\bOpenCode\b|\bCodex\b|\bKimi(?: Code)?\b|AskUserQuestion|TaskCreate|TaskUpdate|TaskList|\$CLAUDE_PLUGIN_ROOT|~\/\.claude|(^|[\s`(>])\/(?:ultra-[a-z-]+|learn)(?=$|[\s`,.;):])/m;
  for (const name of [...NEUTRAL_SKILLS].sort()) {
    const files = walk(path.join(SKILLS_ROOT, name), (file) => file.endsWith('.md'));
    for (const file of files) {
      assert.doesNotMatch(
        fs.readFileSync(file, 'utf8'),
        hostBindings,
        `${path.relative(ROOT, file)} contains a host-specific invocation`,
      );
    }
  }
});

test('research preserves the complete semantic workflow through focused references', () => {
  const root = path.join(SKILLS_ROOT, 'ultra-research');
  assert.ok(fs.existsSync(path.join(root, 'references')), 'ultra-research must use references/');
  assert.ok(!fs.existsSync(path.join(root, 'steps')), 'ultra-research steps/ duplicates the main workflow');
  assert.deepEqual(
    fs.readdirSync(path.join(root, 'references')).sort(),
    [
      '00-problem-validation.md', '01-opportunity-discovery.md', '02-market-assessment.md',
      '03-competitive-landscape.md', '04-product-strategy.md', '05-assumptions-validation.md',
      '10-user-personas.md', '11-user-scenarios.md', '20-user-stories.md',
      '21-features-scope.md', '22-success-metrics.md', '30-architecture-context.md',
      '31-solution-strategy.md', '32-building-blocks.md', '40-deployment.md',
      '41-quality-risks.md', '99-synthesis.md',
    ],
  );
  const skillText = fs.readFileSync(path.join(root, 'SKILL.md'), 'utf8');
  assert.match(skillText, /recommend the smallest sufficient set of applicable catalog areas/i);
  assert.match(skillText, /user (?:selects|chooses), modifies, delegates, or defers/i);
  assert.match(skillText, /host(?:'s)? native (?:structured )?question/i);
  assert.match(skillText, /persist the accepted coverage/i);
  assert.match(
    skillText,
    /focused baseline coverage[\s\S]*full.*adoption[\s\S]*custom[\s\S]*change-bound/i,
  );
  assert.match(skillText, /Omitted\s+catalog areas create no DB step/i);
  assert.match(skillText, /metadata\.selection_reason/i);
  assert.doesNotMatch(skillText, /host model owns investigation, synthesis, and coverage judgment/i);
  assert.doesNotMatch(skillText, /disposition for every catalog area/i);
  const skillLines = skillText.split('\n').length;
  assert.ok(skillLines <= 120, `ultra-research/SKILL.md has ${skillLines} lines; expected at most 120`);
});

test('human-agent alignment uses one canonical resumable decision protocol', () => {
  const reference = path.join(SKILLS_ROOT, 'ultra-think', 'references', 'decision-dialogue.md');
  assert.ok(fs.existsSync(reference), 'canonical decision dialogue reference is missing');
  const protocol = fs.readFileSync(reference, 'utf8');
  for (const tool of [
    'decision.list', 'decision.thread_start', 'decision.open', 'decision.resolve',
    'decision.delegate', 'decision.defer', 'decision.supersede', 'decision.complete',
    'decision.checkpoint',
  ]) {
    assert.match(protocol, new RegExp(`\\b${tool.replace('.', '\\.')}\\b`), `${tool} is absent from the protocol`);
  }
  assert.match(protocol, /Ask one question only/i);
  assert.match(protocol, /STOP is mandatory/i);
  assert.match(protocol, /never store raw prompts or\s+transcripts/i);
  assert.match(protocol, /fact acquisition autonomous and decision authority explicit/i);
  assert.match(protocol, /inspect[\s\S]*suggest[\s\S]*ask[\s\S]*normalize[\s\S]*persist/i);
  assert.match(protocol, /DB treats (?:the )?normalized intent as current authority/i);
  assert.match(protocol, /does not prove that the user\s+selected it/i);

  for (const name of ['ultra-init', 'ultra-research', 'ultra-think', 'ultra-change', 'ultra-plan']) {
    const { text } = sourceSkill(name);
    assert.match(text, /decision-dialogue\.md/, `${name} must use the canonical decision protocol`);
  }
  assert.match(sourceSkill('ultra-research').text, /not\s+(?:a\s+)?(?:mandatory\s+)?questionnaire/i);
  assert.match(
    sourceSkill('ultra-research').text,
    /Reuse the final research acceptance or current artifact checkpoint[\s\S]*do not ask\s+for an equivalent approval again/i,
  );
  assert.match(sourceSkill('ultra-change').text, /Ask only when a choice changes accepted product intent/i);
  assert.match(sourceSkill('ultra-change').text, /model owns reversible\s+implementation detail/i);
  assert.match(sourceSkill('ultra-think').text, /decision\.complete[\s\S]*not another owner approval/i);
  assert.match(sourceSkill('ultra-plan').text, /EXPAND[\s\S]*SELECTIVE[\s\S]*HOLD[\s\S]*REDUCE/i);
  assert.match(sourceSkill('ultra-plan').text, /recommend[\s\S]*host(?:'s)? native question/i);
  assert.match(
    sourceSkill('ultra-test').text,
    /recommend[\s\S]*user to select,\s*modify, delegate, or defer/i,
  );
});

test('public workflow skills return control to the adaptive capability graph', () => {
  const graphSkills = [
    'ultra-init', 'ultra-research', 'ultra-change', 'ultra-plan', 'ultra-dev',
    'ultra-test', 'ultra-review', 'ultra-deliver', 'ultra-status', 'ultra-think',
    'ultra-doctor',
  ];
  for (const name of graphSkills) {
    const { text } = sourceSkill(name);
    assert.match(text, /allowed[_ ]transitions/i, `${name} does not return MCP capability choices`);
    assert.doesNotMatch(
      text,
      /^\s*(?:canonical|exact) next (?:action|route)\s*:/im,
      `${name} exposes a retired semantic-route field`,
    );
  }
  assert.match(sourceSkill('ultra-init').text, /does not perform product research/i);
  assert.match(sourceSkill('ultra-research').text, /\bultra-change\b/);
  assert.match(sourceSkill('ultra-change').text, /research, plan, context, dev, test,\s*review, and deliver(?:y)? remain (?:independent|separate)/i);
  assert.match(sourceSkill('ultra-dev').text, /do not replace aggregate\s*change testing or review/i);
  assert.match(sourceSkill('ultra-deliver').text, /host-owned effect after Ultra delivery/i);
});

test('workflow skills name every durable DB step they are responsible for following', () => {
  for (const [kind, steps] of Object.entries(WORKFLOW_DEFINITIONS)) {
    const { text } = sourceSkill(`ultra-${kind}`);
    for (const { id } of steps) {
      assert.match(
        text,
        new RegExp(`(?:^|[^a-z0-9-])${id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?:$|[^a-z0-9-])`, 'm'),
        `ultra-${kind} must explain how to follow durable workflow step ${id}`,
      );
    }
  }
});

test('command markdown files are English thin launchers', () => {
  const commands = fs.readdirSync(COMMANDS_ROOT).filter((name) => name.endsWith('.md')).sort();
  for (const name of commands) {
    const file = path.join(COMMANDS_ROOT, name);
    const text = fs.readFileSync(file, 'utf8');
    const { fm, body } = parseFrontmatter(text);
    assert.ok(fm && typeof fm['workflow-ref'] === 'string', `${name} must route to one skill`);
    assert.doesNotMatch(text, /[\u3400-\u9fff]/u, `${name} contains Han-script prompt text`);
    assert.ok(body.split('\n').length <= 12, `${name} duplicates workflow instructions instead of remaining a thin launcher`);
    assert.match(body, /follow/i, `${name} must direct the host to follow the referenced skill`);
  }
});

test('collaboration skills remain explicit companions, not neutral workflow dependencies', () => {
  for (const name of COLLAB_SKILLS) assert.ok(PACKAGED_SKILLS.has(name));
  for (const name of NEUTRAL_SKILLS) assert.ok(!COLLAB_SKILLS.has(name));
});

test('agent prompts use the current evidence-based review contract', () => {
  const forbidden = [
    { pattern: /[\u3400-\u9fff]/u, label: 'Han-script instruction text' },
    { pattern: /\bultra-review-findings-v1\b/i, label: 'retired review schema' },
    { pattern: /\bCLAUDE\.md\b/, label: 'host-specific handbook binding' },
    { pattern: /\bContext7\b|mcp__context7|\bExa MCP\b|mcp__exa|\bGemini\b|\bRTK\b|\bgraphify\b/i, label: 'retired or external tool binding' },
    { pattern: /\babsolute P0\b|\bnon-negotiable P0\b|\bP1 count\s*>\s*\d+|\bconfidence\s*>=?\s*\d+/i, label: 'mechanical severity or verdict threshold' },
    { pattern: /\bforbidden mock patterns?\b|\bmock violations?\b/i, label: 'blanket test-double ban' },
    { pattern: /\bFour-Dimension Scoring\b|\baggregate score\b/i, label: 'unsupported design score' },
  ];

  for (const file of walk(AGENTS_ROOT, (candidate) => candidate.endsWith('.md'))) {
    const text = fs.readFileSync(file, 'utf8');
    const { fm, body } = parseFrontmatter(text);
    assert.ok(fm && typeof fm.description === 'string', `${path.basename(file)} needs a concise description`);
    assert.ok(fm.description.replace(/\s+/g, ' ').trim().length <= 400, `${path.basename(file)} description is prompt-heavy`);
    assert.ok(body.split('\n').length <= 120, `${path.basename(file)} body exceeds the bounded worker prompt budget`);
    for (const { pattern, label } of forbidden) {
      assert.doesNotMatch(text, pattern, `${path.relative(ROOT, file)} contains ${label}`);
    }
  }

  for (const name of ['review-spec', 'review-code', 'review-comments', 'review-design', 'review-errors', 'review-tests']) {
    const text = fs.readFileSync(path.join(AGENTS_ROOT, `${name}.md`), 'utf8');
    assert.match(text, /ultra-review-findings-v2/, `${name} must write the current specialist artifact`);
    assert.match(text, /SCHEMA_PATH/, `${name} must receive a host-resolved schema path`);
  }
  const coordinator = fs.readFileSync(path.join(AGENTS_ROOT, 'review-coordinator.md'), 'utf8');
  assert.match(coordinator, /ultra-review-summary-v2/, 'review-coordinator must write the current summary artifact');
  assert.match(coordinator, /SCHEMA_PATH/, 'review-coordinator must receive a host-resolved schema path');
  assert.match(coordinator, /spec_fidelity/);
  assert.match(coordinator, /engineering_standards/);
});

test('focused references do not duplicate standalone policy skills', () => {
  const references = fs.readdirSync(path.join(SKILLS_ROOT, 'code-review-expert', 'references')).sort();
  assert.deepEqual(references, ['correctness-reliability.md', 'design-boundaries.md', 'removal-plan.md']);
});

test('repository documents the source prompt boundary separately from runtime prompts', () => {
  const authoring = fs.readFileSync(path.join(ROOT, 'docs', 'SKILL-AUTHORING.md'), 'utf8');
  assert.match(authoring, /Source frontmatter contains only `name` and `description`/);
  assert.match(authoring, /standards do not prohibit Chinese/i);
  assert.match(authoring, /Comparison is appropriate only when/i);
});
