#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const Ajv = require('ajv/dist/2020');
const addFormats = require('ajv-formats');
const yaml = require('js-yaml');

const repoRoot = path.resolve(__dirname, '..', '..');
const skillsRoot = path.join(repoRoot, 'skills');
const schemaPath = path.join(__dirname, '..', 'schemas', 'skill-manifest.schema.json');
const migrationNotesPath = path.join(__dirname, '..', 'migration-notes.md');

if (!fs.existsSync(schemaPath) || !fs.existsSync(skillsRoot)) {
  console.log('skill-manifest schema or skills/ missing, skip');
  process.exit(0);
}

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);
const validate = ajv.compile(JSON.parse(fs.readFileSync(schemaPath, 'utf8')));

const skillDirs = fs
  .readdirSync(skillsRoot, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name);

let total = 0;
let pass = 0;
let fail = 0;
const failures = [];

function parseFrontmatter(text) {
  if (!text.startsWith('---')) return null;
  const end = text.indexOf('\n---', 3);
  if (end === -1) return null;
  return yaml.load(text.slice(3, end));
}

for (const dir of skillDirs) {
  const skillFile = path.join(skillsRoot, dir, 'SKILL.md');
  if (!fs.existsSync(skillFile)) {
    continue;
  }
  total++;
  const text = fs.readFileSync(skillFile, 'utf8');
  const fm = parseFrontmatter(text);
  if (!fm) {
    console.error(`  FAIL ${dir}: no parseable YAML frontmatter`);
    failures.push({ dir, errors: ['no frontmatter'] });
    fail++;
    continue;
  }
  const ok = validate(fm);
  if (ok) {
    console.log(`  ok ${dir}`);
    pass++;
  } else {
    const errs = validate.errors.map((e) => `${e.instancePath || '/'} ${e.message}`);
    console.error(`  FAIL ${dir}:\n      ${errs.join('\n      ')}`);
    failures.push({ dir, errors: errs });
    fail++;
  }
}

const passRate = total === 0 ? 1 : pass / total;
console.log(`skills: ${pass}/${total} passed (${(passRate * 100).toFixed(0)}%)`);

if (failures.length > 0) {
  const lines = [
    '# Skill manifest migration notes',
    '',
    `Generated by spec/scripts/validate-skills.cjs at ${new Date().toISOString()}`,
    '',
    'Each entry is a SKILL.md whose frontmatter does not match',
    '`spec/schemas/skill-manifest.schema.json`. Add the missing fields',
    '(or update the schema) before Phase 3 implements skill.resolve.',
    '',
  ];
  for (const f of failures) {
    lines.push(`## ${f.dir}`);
    lines.push('');
    for (const e of f.errors) {
      lines.push(`- ${e}`);
    }
    lines.push('');
  }
  fs.writeFileSync(migrationNotesPath, lines.join('\n'));
  console.log(`note: wrote ${migrationNotesPath} (${failures.length} skills need updates)`);
} else if (fs.existsSync(migrationNotesPath)) {
  fs.unlinkSync(migrationNotesPath);
}

// AC: ≥90% pass rate; record failures but do not fail the gate.
if (passRate < 0.9) {
  console.error(`FAIL skill manifest pass rate ${(passRate * 100).toFixed(0)}% < 90% threshold`);
  process.exit(1);
}
process.exit(0);
